image:
  file: .gitpod/Dockerfile
tasks:
  - init: |
      rustup default 1.67.0
      cargo test --no-run
      cargo install cargo-insta
      cargo install git-branchless && git branchless init
vscode:
  extensions:
    - "matklad.rust-analyzer"
