FROM gitpod/workspace-full

# The following environment variables are necessary for `cargo test` to pass.
# Determined by running `which git` and `git --exec-path`.
ENV PATH_TO_GIT=/usr/bin/git GIT_EXEC_PATH=/usr/lib/git-core
