name: Nix on Linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    name: nix-build
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --print-build-logs --show-trace --override-input nixpkgs github:NixOS/nixpkgs
